name: Build BookstoreUI

on:
  push:
    paths:
      - bookstore-ui/**
    branches:
      - '**'

jobs:
  build-ui:
    name: Build bookstore-ui
    runs-on: ubuntu-latest
    env:
      working-directory: ./bookstore-ui
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/bookstore-ui
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ env.working-directory }}/package-lock.json

      #- name: Test
      #  run: CI=true npm test

      - name: Build
        run: |
          npm ci
          npm run build

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and Publish Docker Image
        run: |
          docker build -t $DOCKER_IMAGE_NAME .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push $DOCKER_IMAGE_NAME